### ISSUE TITLE
pyfvs not in python search path after open-fvs installation

### ISSUE THREAD

**Issue by peteWT** [tharen/PyFVS#12]
Hi,

Ive just installed open-fvs with the `-DWITH_PYMOD=ON` flag and the process completed without errors. I don't seem to be able to load the pyfvs libraries though.:
`ImportError: No module named pyfvs`

I've checked python path and its not in there. Any suggestions?

Peter

System:
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=2
DISTRIB_CODENAME=betsy
DISTRIB_DESCRIPTION="LMDE 2 Betsy"
PRETTY_NAME="Linux Mint LMDE"
NAME="Linux Mint LMDE"
ID=linuxmint
ANSI_COLOR="1;31"

Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux

**Comment by tharen** [comment]
Peter,

It sounds like the pyfvs package is not being built completely or is not installing as expected.  For starters try reconfiguring CMake with `-DWITH_PYEXT=ON` instead of `-DWITHPYMOD=ON`.  This was changed recently and I see that not all references were updated.  If that does not do it then verify that the pyfvs package is being copied to your installation location and that the extension libraries are being compiled, eg `pyfvspnc.so`.  Finally, verify that your installation prefix is available in the PYTHONPATH environment variable.

Hope that helps.  Let me know.  There are some notable gaps in the still limited documentation.  I'll be sure to include this.

Tod

**Comment by peteWT** [comment]
Hi Tod,

Thanks for the hint, no luck. I decided to try to compile open-fvs with this repo instead of the openfvs on sourceforge (any particular reason why I should use on or the other?).  My procedure and results follow:
`$ chmod u+x config_build.sh
$ ./config_build.sh
-- Build Type:Debug
-- Configure for native architecture target.
-- Native target architecture is 64 bit
-- Native target OS is *NIX
-- Add GCC compiler flags.
-- Add -fPIC for UNIX targets.
-- Variant source list: pnc - /home/pete/src/PyFVS/bin/FVSpnc_sourceList.txt
-- Variant source list: wcc - /home/pete/src/PyFVS/bin/FVSwcc_sourceList.txt
-- FVS Variants = (2) pnc;wcc
-- Source Root = /home/pete/src/PyFVS
-- Build static SQL objects.
-- Build static FFE objects.
You have called ADD_LIBRARY for library common_objs without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configure variants: pnc;wcc
-- Variant Dir = /home/pete/src/PyFVS/bin/pnc
-- Source List File: /home/pete/src/PyFVS/bin/FVSpnc_sourceList.txt
-- Configure variant: pnc
-- CMake Build Type: Debug
-- Profiling: OFF
-- source_list: /home/pete/src/PyFVS/bin/pnc/sourcelist.txt
-- fvsexe: FVSpnc
-- fvslib_shared: libFVSpnc
-- Configure and build the Python extension.
CMake Error: File /home/pete/src/PyFVS/bin/pnc/../../setup.py.in does not exist.
CMake Error at pnc/CMakeLists.txt:280 (configure_file):
  configure_file Problem configuring file

-- **\* End PyMod Configuration ***
-- Variant Dir = /home/pete/src/PyFVS/bin/wcc
-- Source List File: /home/pete/src/PyFVS/bin/FVSwcc_sourceList.txt
-- Configure variant: wcc
-- CMake Build Type: Debug
-- Profiling: OFF
-- source_list: /home/pete/src/PyFVS/bin/wcc/sourcelist.txt
-- fvsexe: FVSwcc
-- fvslib_shared: libFVSwcc
-- Configure and build the Python extension.
CMake Error: File /home/pete/src/PyFVS/bin/wcc/../../setup.py.in does not exist.
CMake Error at wcc/CMakeLists.txt:280 (configure_file):
  configure_file Problem configuring file

-- **\* End PyMod Configuration ***
-- Configuring incomplete, errors occurred!
See also "/home/pete/src/PyFVS/bin/CMakeFiles/CMakeOutput.log".
`
Thanks very much for your response!

**Comment by tharen** [comment]
Peter,

Sorry for the delayed responses.  I wanted to test it on my end before sent you off course.

Obviously documentation on the build process and usage is lagging behind or non existent.  I'll try to work on that.  The branch on SourceForge is definitely stale.  It's was my intention to keep them in sync, but I haven't had as much time as I'd hoped to work on this.  For now my goal is to keep my work here on GitHub, merging changes in from the core FVS code periodically.

I've modified the configure_build.sh script a bit. I had originally set it up to work with the Travis-CI environment. Also, I see that when I changed the CMake variable WITH_PYMOD to WITH_PYEXT I failed to update the name everywhere.  If you pull my changes the following should work for you from the root of the checkout folder:

```
  # from the repository root folder
  source ../configure_build.sh
  make
  make install
  cd Open-FVS/python
```

`make install` should put two .so library files within Open-FVS/python, as well as a pyfvs folder.  From dist/python `python -c "import pyfvs"` should work.  If you have nose-parameterized installed the test script test_variants.py should run.

```
  # from Open-FVS/python
  python -m unittest test/test_variants.py
```

All that said, as I've had time I've been working primarily in the dev branch of this repository.  You may have better luck with that.  I've been trying to improve the build process, added more to to the pyfvs module, and started working on some packaging that will eventually make it's way to PyPI.

Tod

**Comment by peteWT** [comment]
Thanks Tod!

`source ./config_build.sh` completes successfully, however make chokes on building FOEFM C objects:

`2 warnings generated.
[  1%] Building C object CMakeFiles/ffe_lib.dir/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c.o
/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c:13:10: fatal error: 'windows.h'
      file not found
#include <windows.h>`

I was under the impression I could build this on *.nix 

Any hints? Thanks again.

Peter

**Comment by tharen** [comment]
Yes it builds on Ubuntu 14.04 64 bit for sure.  It should not be looking
for the windows header files.  There is probably a glitch in the compiler
flags that Cmake is including.  I'll take a look.

Tod

**Comment by tharen** [comment]
I've added a -DANSI flag to the GCC definitions in the CMake configuration.  fm_fofem.c, and perhaps others, require a dummy "WINAPI" def when compiling on *nix.  It may be that your particular CMake/Make/GCC combination is not providing this by default.  Something unique to the Linux Mint packaging perhaps.  Pull the current commit from master and try again.

Tod

**Comment by NewForestsUS** [comment]
Hi Tod,

I've switched over to OSX to work on this. Using the `dev` branch I can sucessfuly execute `./config_build.sh` but make results in some strange errors:

`$ make
[  0%] Built target mkdbsTypeDefs
[  0%] Built target gen_dbstypedefs
[  1%] Built target sql_lib
[  1%] Built target common_objs
[  1%] Building C object CMakeFiles/ffe_lib.dir/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c.o
clang: warning: argument unused during compilation: '-cpp'
/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c:64:38: error: parameter named
      'fm_fofem_' is missing
    extern __declspec(dllexport) int fm_fofem_ ( // GCC compiler, Windows OS
                                     ^
/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c:78:5: error: redefinition of
      parameter 'fm_fofem_'
int fm_fofem_ (
    ^
/Users/pete/src/PyFVS/fire/fofem/src/fm_fofem.c:64:38: note: previous
      declaration is here
    extern __declspec(dllexport) int fm_fofem_ ( // GCC compiler, Windows OS`

make generates 20 errors of this kind, all from `fm.fofem.c` and then says:

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.`

Thanks for your suggestions.

Peter

**Comment by tharen** [comment]
Peter,

I recently helped another user get going with OSX, so I know it will
compile.  The dev branch is still the place to start.  So you're on the
right track.

I have no experience with the CLANG compiler.  It appears that is where the
errors are originating. If you can use the GCC compilers you might have
better luck.

Let me know how it goes.

Tod

**Comment by peteWT** [comment]
Tod,

Can't for the life of me get cmake to use gcc instead of clang. Tried adding this to config_build.sh:
`-DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++` but compiler is still clang.

Any suggestions?

Thanks!

**Comment by tharen** [comment]
That seems like the correct way to go. In the build/pnc subfolder there
should be a file called cmakevars-pnc.txt.  This contains a dump of all the
CMake variables after the configuration is complete.  You might look in
there to see what those variables are actually being assigned to.

**Comment by tharen** [comment]
Here are a few notes from helping another OSX user.

1) Start with a fresh CMake configuration by deleting the build folder,
e.g. 'rm -rf bin/build'.  Or at least the CMakeFiles folder and
CMakeCache.txt.
2) Ensure you have the most recent revisions from GitHub, 'git checkout
dev', 'git pull'
3) Make sure gcc and gfortran are present in the current environment, gcc
--version, gfortran --version.
4) Run the configuration script again, 'source config_build.sh'.
5) fm_fofem.c is looking for the 'ANSI' definition on non windows systems.
CMakeLists.txt should be add this, but it could be forced by adding -DANSI
to the CMake configuration command line.
6) Install libtool if you receive and error message like "ld: library not
found for -lltdl"
7) Build the Python extension by moving to the bin/build/dist/python folder
and running 'python setup.py build_ext'.
7) If the build is successful the tests can be run if the Python libraries
nose2, and nose-parameterized are installed.
8) For testing and development the extension can be installed with 'pip
install -e .' from the bin/build/dist/python folder.

Tod
